image: node:lts

create-pages:
  script:
    - mkdir -p public
    - git archive --format=tar HEAD | tar -x -C public
  pages:
    publish: public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
